# Generated by Django 3.2.9 on 2021-11-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GradeSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseDescription',
            field=models.CharField(max_length=300),
        ),
    ]
