# Generated by Django 3.2.9 on 2021-11-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GradeSystem', '0007_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_instructor',
            field=models.BooleanField(default=False, verbose_name='instructor status'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_student',
            field=models.BooleanField(default=False, verbose_name='student status'),
        ),
    ]
